# Generated by Django 5.1.2 on 2024-10-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_remove_driver_email_remove_driver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
